import type { Metadata } from "next";
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
});

import Navbar from '@/components/navbar';
import "./globals.css";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Peejay Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-[#ECECEC] `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
